language: node_js
node_js:
- 8.9.4
deploy:
  provider: script
  script: dpl --provider=npm --email=$NPM_EMAIL --api-key=$NPM_TOKEN
  on:
    tags: true
    repo: OleConsignado/vcs-hosted-k8s-helm-installer
