language: node_js
node_js:
  - 8.9.4
deploy:
  provider: npm
  email: matheusneder@gmail.com
  api_key:
    secure: ijnIzWckQMJhlzCzEbHM6kBdVwZDBlxk1SqzOjdYFqT6mssEl6JoTBZGJLGeVBbHg1B4AwC22J+Jrss6g6z/8mjJaOLLQCtUIEJvkNg8Q3pHlgsasC/Uuo67iDkTjXDJrgcldMv+7HVTmiysGOPXv8PPdy1gTB6Nc7dY8M1izWldNpeXRD3nOVqWGKCAoixmoQ4GOfCQaOCFrL2V2aaAybqJFUwO5dZoDZItYYrJGZJufSfejO8t5afcGFzT2Mwmu4/fc0kkRziNIHNR8YlGp0m2cOTlVFLN6ElREBtMH7pK/RwdmnYhcO4or3gEPf+GZI6ZR+YzGIJ7qNi1jjocd/lSRvW72OYJBm+YrUZQhMu7s1UqMFSjWCdupLyRP03h/XwFwIyt6YlK1FTVeJ2tOJd+6xWgvc1F6m/IORhPkoX3/+80wiGqAPznkvp1kKwJOnw7LetyLdW8922vPDpOMOaYpjeRDJuXudv7MdU8Wp7IwquRoZVyzXHhBH4rRHSL4Vsep5Ypas/07hUB5NfvmzIwRS8VlMd/DHRm0pISsScaX7gb51vCDi/Z6qM+YCqNMd2IujTmhEYZgP8nxnbwPkJrINIrzhR8wy9oEtQLurWQi14iTWbiaFy1ktqBIBtCU14hC2T5vhg2jBX1NHTN3/4o5ADp31BhguqagpSsdVg=
  on:
    tags: true
    repo: mnconsulting/vcs-hosted-k8s-helm-installer
